config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#landing_page'
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  post 'static_pages/thank_you'
  
  resources :articles do
    resources :comments
  end

  resources :users
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  	@featured_article = Article.first
  end

  def index
  end

  def about
  end

  def contact
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@name, @email, @message).deliver_now    
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<!-- Landing Header -->
<div class="container">
	<h1>About | Jason's Blog</h1>
	<p>Follow me on my journey into the Rails wilderness as I discover new and fastastic treasures and unexpected creatures.</p>
	
</div><!-- /container-fluid -->

app/views/static_pages/contact.html.erb
<div class="container">
  <h1>Contact | Jason's Blog</h1>
  <h3 class="center">Contact us:</h3>

  <%= flash[:notice] %>

  <%= form_tag("/static_pages/thank_you") do %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        <%= label_tag :name, "Name:" %>
        <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
      </div>
      <div class="form-group">
        <%= label_tag :email, "Email Address:" %>
        <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
      </div>
      <div class="form-group">
        <%= label_tag :message, "Message:" %>
        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
      </div>
      <%= submit_tag "Send", class: "btn btn-primary form-search" %> 
    </div>
  </div>
  <% end %> 
</div>  

app/views/static_pages/index.html.erb
<!-- Landing Header -->
<div class="container">
	<h1>Index | Jason's Blog</h1>
	<p>Link to show, edit and delete posts.</p>
	
</div><!-- /container-fluid -->

app/views/static_pages/landing_page.html.erb
<div class="container">
	<!-- Landing Header -->
	<div class="center jumbotron">
	  <h1>Welcome to my blog.</h1>
	  <h3>Hope you enjoy my journey in Web Development.</h3> 
	</div><!-- /container-fluid -->

	<div class="row">
		<div class="center">
        <h1>Feature Article</h1>  
    </div>
    <hr>
    <div class="col-md-4">
      <div class="img-container">    
        <%= image_tag(@featured_article.image_url, class: "img-responsive") %>
      </div>	               
    </div>

    <div class="col-md-8">
      <h2><%= @featured_article.title %></h2>
      <div><%= @featured_article.description %></div>
      <hr>
      <%= link_to 'Read More', article_path(@featured_article), class: "btn btn-success" %>
    		        
    </div>    
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
        <%= @featured_article.text %> 
    </div>
	</div>	
	<hr>

	<div class="center">
        <%= link_to 'Show Other Articles', articles_path, 
										class: "btn btn-primary"  %>  
  </div>

</div>

app/views/static_pages/thank_you.html.erb
<div class="container">  
  <div class="panel panel-default">
    <div class="panel-body">
      <p>Thank you. We have received your message and will be in contact shortly.</p>
      <p><%= link_to "Click here to go back to the HOME PAGE.", root_path %></p>
    </div><!-- / panel-body -->
  </div><!-- / panel -->
</div>