config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#landing_page'
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  post 'static_pages/thank_you'
  
  resources :articles do
    resources :comments
  end

  resources :users
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
  

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2015 Jason's Blog Rails Demo
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
      <li><%= link_to 'Show Articles', articles_path %></li>     
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container navbar-container">

    <%= link_to "Jason Mans' Blog", root_path, id: "logo" %>
    
    <!-- Smaller and Mobile Screen Nav bar-->
    <div class="navbar-header">
      <!-- Navbar Toggle Button-->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">            
        <span class="sr-only">Toggle Navigation </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> <!-- /navbar toggle button-->      
    </div> <!-- /navbar-header {Mobile Screen}-->

    <nav class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>
        <li><%= link_to 'Show Articles', articles_path %></li> 
        
        <% if user_signed_in? %>

          <!-- Admin Button -->
          <% if signed_in? && current_user.admin? %>
             <li>
                <%= link_to "ADMIN VIEW", users_path %>              
            </li>
          <% end %> 
           
          <!-- Account Dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            </ul>
          </li>

        <!-- Not Logged-in -->
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %>
        <% end %>        

      </ul>

      <!-- Search Form -->
      <%= render 'layouts/search_form' %>

    </nav>
  </div>
</header>

app/views/layouts/_notices_and_alerts.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>

    <% alert_type = 'success' if message_type === 'notice' %>
    <% alert_type = 'danger' if message_type === 'alert' %>
    <div id="<%= message_type %>" class="alert alert-<%= alert_type %>"><%= message %></div>  

  <% end %>
</div>  

app/views/layouts/_search_form.html.erb
<ul class="navbar-form navbar-right">  
  <li>
    <%= form_tag("/articles", method: "get", class: "navbar-form navbar-right", role: "search" ) do %>
      <div class="form-group">
        <%= label_tag(:q, "Search for:", id: "label-search", class: "form-search") %>
        <%= text_field_tag :q, nil, class: "form-control form-search", placeholder: "Item" %>
      </div>
      <%= submit_tag("Go", class: "btn btn-primary form-search", id: "btn-search") %>            
    <% end %>
  </li>
</ul>   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Blog Web App</title>
    
    <!-- Custom styles in assets folder linked here -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Custom javascript in assets folder linked here -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <!--  The Rails method csrf_meta_tags, which prevents cross-site request forgery (CSRF), a type of malicious web attack. -->
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- Header -->
    <%= render 'layouts/header' %>

    <!-- Devise "notices" and "alerts" -->
    <%= render 'layouts/notices_and_alerts' %>

    <!-- Body -->
    <%= yield %>

      <!-- Footer -->
      <div class="container">
        <%= render 'layouts/footer' %>
      </div>

  </body>
</html>